<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Ghost Log Archive Export</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: 11px; color: #1a1a1a; margin: 0; padding: 40px; background: #fff; }
        .header { text-align: center; border-bottom: 3px solid #000; padding-bottom: 15px; margin-bottom: 25px; }
        .header h1 { margin: 0; font-size: 24px; text-transform: uppercase; letter-spacing: 4px; font-weight: 900; }
        .header p { margin: 8px 0 0; font-size: 11px; color: #555; text-transform: uppercase; letter-spacing: 2px; font-weight: bold; }
        .meta { margin-bottom: 30px; line-height: 1.6; }
        .meta-grid { display: table; width: 100%; border-bottom: 1px solid #eee; padding-bottom: 15px; }
        .meta-item { display: table-cell; width: 33.33%; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; table-layout: fixed; }
        th { background: #f8f9fa; text-align: left; padding: 12px 8px; border-bottom: 2px solid #000; text-transform: uppercase; font-size: 10px; font-weight: 900; }
        td { padding: 10px 8px; border-bottom: 1px solid #eee; vertical-align: top; overflow-wrap: break-word; }
        .timestamp { color: #666; font-weight: bold; width: 130px; }
        .user { font-weight: 800; width: 110px; }
        .action { color: #2563eb; font-weight: 900; text-transform: uppercase; font-size: 9px; width: 130px; }
        .payload { color: #444; font-family: 'Consolas', 'Monaco', monospace; font-size: 9px; line-height: 1.4; }
        .footer { position: fixed; bottom: 20px; width: 100%; text-align: center; font-size: 9px; color: #999; text-transform: uppercase; letter-spacing: 1px; }
        
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
            .header { border-bottom-color: #000 !important; }
        }

        .print-btn {
            position: fixed; top: 20px; right: 20px; background: #000; color: #fff; border: none; padding: 10px 20px; 
            border-radius: 5px; cursor: pointer; font-weight: bold; text-transform: uppercase; font-size: 12px; z-index: 100;
        }
    </style>
</head>
<body onload="window.print()">
    <button class="no-print print-btn" onclick="window.print()">Print / Save as PDF</button>

    <div class="header">
        <h1>GHOST LOG ARCHIVE</h1>
        <p>ITcloud Obsidian OS • Neural Intelligence Audit</p>
    </div>

    <div class="meta-grid">
        <div class="meta-item">
            <strong>GENERATED BY:</strong><br>
            {{ auth()->user()->name }}
        </div>
        <div class="meta-item">
            <strong>TIMESTAMP:</strong><br>
            {{ now()->format('d.m.Y H:i:s') }}
        </div>
        <div class="meta-item">
            <strong>EXTRACTED NODES:</strong><br>
            {{ count($logs) }} RECORDS
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th style="width: 130px;">TIMESTAMP</th>
                <th style="width: 110px;">OPERATIVE</th>
                <th style="width: 130px;">DIRECTIVE</th>
                <th>PAYLOAD MATRIX</th>
            </tr>
        </thead>
        <tbody>
            @foreach($logs as $log)
                <tr>
                    <td class="timestamp">{{ $log->created_at->format('d.m.Y H:i:s') }}</td>
                    <td class="user">{{ $log->user->name ?? 'SYSTEM AUTO' }}</td>
                    <td class="action">{{ str_replace('_', ' ', $log->action) }}</td>
                    <td class="payload">
                        @if($log->new_values)
                           {{ json_encode($log->new_values) }}
                        @else
                            <i style="opacity: 0.5;">NO_DATA_PAYLOAD</i>
                        @endif
                        <div style="margin-top: 4px; font-size: 8px; color: #aaa;">SRC: {{ $log->ip_address }}</div>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        CLASSIFIED DOCUMENT • OBSIDIAN OS SECURE AUDIT • PRESERVE DATA INTEGRITY
    </div>
</body>
</html>
